name: CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/main.yml'
      - 'packages/**'

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.30

      - name: Build project
        run: bun install

      - name: Deploy Client
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          SOURCE: 'package/client/dist'
          TARGET: '/var/www/openbomber'
          ARGS: "-rlgoDzvc -i --delete"

      - name: Deploy Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          SCRIPT_BEFORE: pm2 ls | grep openbomber && pm2 delete openbomber || echo ""
          SCRIPT_AFTER: cd /root/openbomber && pm2 start npm --name openbomber index.js
          SOURCE: 'package/server/dist'
          TARGET: '/root/openbomber'
          ARGS: "-rlgoDzvc -i --delete"
        